# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Suki
site_url: https://kb.solsynth.dev
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
plugins:
  - meta
  - social
  - search
  - awesome-nav
  - git-authors
  - glightbox
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
